# Generated by Django 2.2 on 2021-11-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste_app', '0006_auto_20211107_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
