# Generated by Django 2.2 on 2021-11-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste_app', '0009_auto_20211113_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
