# Generated by Django 2.2 on 2021-11-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste_app', '0014_auto_20211117_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
    ]
