# Generated by Django 2.2 on 2021-11-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste_app', '0018_remove_review_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
